--------------------------------------------------------
--  File created - Wednesday-September-24-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table AGENTS
--------------------------------------------------------

  CREATE TABLE "REALBROKERAGE"."AGENTS" 
   (	"AGENT_ID" NUMBER(*,0), 
	"NAME" VARCHAR2(50 BYTE), 
	"REGION" VARCHAR2(30 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CLIENTS
--------------------------------------------------------

  CREATE TABLE "REALBROKERAGE"."CLIENTS" 
   (	"CLINET_ID" NUMBER(*,0), 
	"NAME" VARCHAR2(50 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"REGION" VARCHAR2(30 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROPERTIES
--------------------------------------------------------

  CREATE TABLE "REALBROKERAGE"."PROPERTIES" 
   (	"PROPERTY_ID" NUMBER(*,0), 
	"TITLE" VARCHAR2(100 BYTE), 
	"CATEGORY" VARCHAR2(30 BYTE), 
	"LOCATION" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TRANSACTIONS
--------------------------------------------------------

  CREATE TABLE "REALBROKERAGE"."TRANSACTIONS" 
   (	"TRANSACTION_ID" NUMBER(*,0), 
	"CLIENT_ID" NUMBER(*,0), 
	"PROPERTY_ID" NUMBER(*,0), 
	"AGENT_ID" NUMBER(*,0), 
	"TRANSACTION_DATE" DATE, 
	"AMOUNT" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into REALBROKERAGE.AGENTS
SET DEFINE OFF;
Insert into REALBROKERAGE.AGENTS (AGENT_ID,NAME,REGION) values (101,'Sarah Johnson','Texas');
Insert into REALBROKERAGE.AGENTS (AGENT_ID,NAME,REGION) values (102,'David Lee','Florida');
Insert into REALBROKERAGE.AGENTS (AGENT_ID,NAME,REGION) values (103,'Maria Gomez','California');
REM INSERTING into REALBROKERAGE.CLIENTS
SET DEFINE OFF;
Insert into REALBROKERAGE.CLIENTS (CLINET_ID,NAME,TYPE,REGION) values (201,'Michael Brown','Buyer','Florida');
Insert into REALBROKERAGE.CLIENTS (CLINET_ID,NAME,TYPE,REGION) values (202,'Alice Uwase','Renter','Texas');
Insert into REALBROKERAGE.CLIENTS (CLINET_ID,NAME,TYPE,REGION) values (203,'John Smith','Seller','California');
REM INSERTING into REALBROKERAGE.PROPERTIES
SET DEFINE OFF;
Insert into REALBROKERAGE.PROPERTIES (PROPERTY_ID,TITLE,CATEGORY,LOCATION) values (301,'Sunset Villas','Apartment','Miami');
Insert into REALBROKERAGE.PROPERTIES (PROPERTY_ID,TITLE,CATEGORY,LOCATION) values (302,'Green Valley House','House','Dallas');
Insert into REALBROKERAGE.PROPERTIES (PROPERTY_ID,TITLE,CATEGORY,LOCATION) values (303,'Ocean View Land','Land','Los Angeles');
REM INSERTING into REALBROKERAGE.TRANSACTIONS
SET DEFINE OFF;
Insert into REALBROKERAGE.TRANSACTIONS (TRANSACTION_ID,CLIENT_ID,PROPERTY_ID,AGENT_ID,TRANSACTION_DATE,AMOUNT) values (4001,201,301,102,to_date('20-JAN-25','DD-MON-RR'),250000);
Insert into REALBROKERAGE.TRANSACTIONS (TRANSACTION_ID,CLIENT_ID,PROPERTY_ID,AGENT_ID,TRANSACTION_DATE,AMOUNT) values (4002,202,302,101,to_date('10-FEB-25','DD-MON-RR'),1500);
Insert into REALBROKERAGE.TRANSACTIONS (TRANSACTION_ID,CLIENT_ID,PROPERTY_ID,AGENT_ID,TRANSACTION_DATE,AMOUNT) values (4003,203,303,103,to_date('25-FEB-25','DD-MON-RR'),500000);
--------------------------------------------------------
--  Constraints for Table CLIENTS
--------------------------------------------------------

  ALTER TABLE "REALBROKERAGE"."CLIENTS" ADD PRIMARY KEY ("CLINET_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROPERTIES
--------------------------------------------------------

  ALTER TABLE "REALBROKERAGE"."PROPERTIES" ADD PRIMARY KEY ("PROPERTY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table AGENTS
--------------------------------------------------------

  ALTER TABLE "REALBROKERAGE"."AGENTS" ADD PRIMARY KEY ("AGENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TRANSACTIONS
--------------------------------------------------------

  ALTER TABLE "REALBROKERAGE"."TRANSACTIONS" ADD PRIMARY KEY ("TRANSACTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRANSACTIONS
--------------------------------------------------------

  ALTER TABLE "REALBROKERAGE"."TRANSACTIONS" ADD FOREIGN KEY ("CLIENT_ID")
	  REFERENCES "REALBROKERAGE"."CLIENTS" ("CLINET_ID") ENABLE;
 
  ALTER TABLE "REALBROKERAGE"."TRANSACTIONS" ADD FOREIGN KEY ("PROPERTY_ID")
	  REFERENCES "REALBROKERAGE"."PROPERTIES" ("PROPERTY_ID") ENABLE;
 
  ALTER TABLE "REALBROKERAGE"."TRANSACTIONS" ADD FOREIGN KEY ("AGENT_ID")
	  REFERENCES "REALBROKERAGE"."AGENTS" ("AGENT_ID") ENABLE;
